//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOrdersProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVendor
    {
        public int ProductID { get; set; }
        public int VendorID { get; set; }
        public Nullable<decimal> ProductVendorWholesalePrice { get; set; }
        public Nullable<short> ProductVendorDaysToDeliver { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
